#!/bin/sh

/usr/bin/invoke_app "$@" -C @tool/bin/cc3dwfdrain.sh -t cc3dwfdrain \
                         -u compucell3d-4.2.2 \
                         -w captive \
                         -r none
